#!/bin/sh
export PATH="/c/Program Files/nodejs:$PATH"

echo "🎨 Formatando arquivos com Prettier..."
npx prettier --write "src/**/*.{ts,tsx}"

echo "⏳ Iniciando o build. Por favor, aguarde..."
npm run build
